FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

COPY CarDepreciationApi/*.csproj ./CarDepreciationApi/ .
RUN dotnet restore CarDepreciationApi/CarDepreciationApi.csproj

COPY . . 
RUN dotnet publish CarDepreciationApi/CarDepreciationApi.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 8080
ENTRYPOINT ["dotnet", "CarDepreciationApi.dll"]