// <auto-generated />
using System;
using CarDepreciationApi.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarDepreciationApi.Migrations
{
    [DbContext(typeof(CarDepreciationAppContext))]
    partial class CarDepreciationAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarDepreciationApi.models.entities.MarketData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConditionScore")
                        .HasColumnType("integer");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MarketData");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.Valuation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InputBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InputConditionScore")
                        .HasColumnType("integer");

                    b.Property<int>("InputMileage")
                        .HasColumnType("integer");

                    b.Property<string>("InputModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InputYear")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValuationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Valuation");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.ValuationNeighbor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValuationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId");

                    b.HasIndex("ValuationId");

                    b.ToTable("ValuationNeighbor");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.Valuation", b =>
                {
                    b.HasOne("CarDepreciationApi.models.entities.User", "User")
                        .WithMany("Valuations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.ValuationNeighbor", b =>
                {
                    b.HasOne("CarDepreciationApi.models.entities.MarketData", "MarketData")
                        .WithMany()
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDepreciationApi.models.entities.Valuation", "Valuation")
                        .WithMany("ValuationNeighbors")
                        .HasForeignKey("ValuationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketData");

                    b.Navigation("Valuation");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.User", b =>
                {
                    b.Navigation("Valuations");
                });

            modelBuilder.Entity("CarDepreciationApi.models.entities.Valuation", b =>
                {
                    b.Navigation("ValuationNeighbors");
                });
#pragma warning restore 612, 618
        }
    }
}
